#Dynamically generated, do not commit to version control!
#Wed Jan 14 22:52:31 CST 2026
appApplePackageName=com.shatteredpixel.shatteredpixeldungeon.apple
appExecutable=IOSLauncher
appMainclass=com.shatteredpixel.shatteredpixeldungeon.ios.IOSLauncher
appName=Shattered Pixel Dungeon
appShortVersionName=3.3.3
appVersionCode=887
appVersionName=3.3.3
